import { useEffect, useState } from 'react';
import { ArrowRight, Bot, CheckCircle2, FileText, Leaf } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import PatientShell from '../components/PatientShell';
import { api } from '../services/api';
import type { ClinicalSession } from '../types';

export default function CaseSummary() {
  const [session, setSession] = useState<ClinicalSession | null>(null); const [loading, setLoading] = useState(true); const navigate = useNavigate();
  useEffect(() => { const id = localStorage.getItem('patientId'); if (!id) { navigate('/login'); return; } api.getPatientSessions(id).then(data => setSession(data.sessions.find((item: ClinicalSession) => item.status === 'completed') || null)).finally(() => setLoading(false)); }, [navigate]);
  if (loading) return <PatientShell title="My case summary"><p className="text-slate-500">Loading your case summary…</p></PatientShell>;
  if (!session) return <PatientShell title="My case summary"><section className="grid min-h-[430px] place-items-center rounded-3xl border border-dashed border-[#d8e2d5] bg-white p-8 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#eef5ec] text-[#397152]"><FileText size={27}/></span><h2 className="mt-5 text-2xl font-semibold">Your case summary will appear here.</h2><p className="mx-auto mt-3 max-w-md leading-7 text-slate-500">Complete guided case-taking to turn your answers into a practitioner-ready overview.</p><button onClick={() => navigate('/hospital-selection')} className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#164d3c] px-5 py-3 font-semibold text-white">Start case-taking <ArrowRight size={17}/></button></div></section></PatientShell>;
  const history = session.history || {}; const fields = [{label:'Chief concern', value:history.chiefComplaint}, {label:'Past medical history', value:history.pastMedical?.join(', ')}, {label:'Medications', value:history.medications?.join(', ')}, {label:'Allergies', value:history.allergies?.join(', ')}];
  return <PatientShell title="My case summary"><p className="text-sm font-semibold text-[#397152]">PRE-CONSULTATION CASE</p><div className="mt-2 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-4xl font-semibold tracking-[-.04em]">Your case, organised.</h2><p className="mt-2 text-slate-600">Prepared from your guided responses for practitioner review.</p></div><span className="inline-flex items-center gap-2 rounded-full bg-[#eaf3e9] px-3 py-1.5 text-sm font-semibold text-[#397152]"><CheckCircle2 size={16}/> Ready to review</span></div><section className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-3xl border border-[#dfe6dc] bg-white p-7"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[#eef5ec] text-[#397152]"><Bot size={21}/></span><div><p className="font-semibold">Clinical overview</p><p className="text-sm text-slate-500">From your conversation</p></div></div><dl className="mt-7 divide-y divide-[#edf0eb]">{fields.map(field => <div key={field.label} className="py-4 first:pt-0"><dt className="text-xs font-semibold tracking-[.12em] text-slate-400">{field.label.toUpperCase()}</dt><dd className="mt-2 leading-7 text-slate-700">{field.value || 'Not recorded'}</dd></div>)}</dl></article><article className="rounded-3xl bg-[#164d3c] p-7 text-white"><div className="flex items-center gap-2 text-[#d8e8c8]"><Leaf size={20}/><p className="font-semibold">Ayush overview</p></div><p className="mt-5 text-sm leading-7 text-white/75">Your practitioner can use this section alongside their own assessment.</p><div className="mt-7 grid grid-cols-2 gap-3">{['Prakriti', 'Vikriti', 'Agni', 'Koshtha'].map(label => <div key={label} className="rounded-xl bg-white/10 p-4"><p className="text-xs font-semibold text-white/55">{label.toUpperCase()}</p><p className="mt-2 font-medium">Not assessed</p></div>)}</div></article></section></PatientShell>;
}
